name: dummy_project
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^3.0.0
  dropdown_search: ^0.5.0
  fluttertoast: ^8.0.3
  drag_select_grid_view: ^0.5.1
  image_picker: ^0.8.1+3

  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.1

  google_sign_in: ^5.0.1

  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.2
  geolocator: ^7.0.1
  http: ^0.13.1

  permission_handler: ^6.1.1
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Attari_Salees
      fonts:
        - asset: assets/fonts/Attari_Salees.ttf
        # - asset: fonts/Schyler-Italic.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
